[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.0.1"
name = "eurydice_test_ramework"
dependencies = ["typer", "pytest"]
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
eurydice = "eurydice_test_ramework.core.management:command_line_handler"

[project.urls]
Homepage = "https://github.com/korneyaitmatoff/eurydice_test_framework"