[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test_framework"
dependencies = ["typer", "pytest"]
dynamic = ["version"]

[project.scripts]
testfw = "test_framework.core.management:command_line_handler"

[project.urls]
Homepage = "https://github.com/korneyaitmatoff/test_framework"