[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.0.1"
name = "test_framework"
dependencies = ["typer", "pytest"]
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
testfw = "test_framework.core.management:command_line_handler"

[project.urls]
Homepage = "https://github.com/korneyaitmatoff/test_framework"